<?php include('layout/header.phtml'); ?>
<div class="grid-container">
    <div class="grid-x grid-margin-x">
        <div class="medium-6 cell">
            <h3>
                <?php if ($editedCategory): ?>Edit<?php else: ?>Add<?php endif; ?> a new category
            </h3>
            <?php if (isset($categorySaved) && $categorySaved == true): ?>
                <div class="callout success">
                    Category was saved
                </div>
            <?php elseif (isset($categorySaved) && $categorySaved == false): ?>
                <div class="callout alert">
                    Fill correctly the form
                </div>
            <?php endif; ?>
            <?php if($categoryDeleted ?? false): ?>
                <div class="callout alert">
                    Category was deleted
                </div>
            <?php endif; ?>
            <form action="<?=$baseUrl?>save-category" method="POST">
            <label
            >Name
                <input type="text" placeholder="Name" name="category_name" value="<?=$editedCategory->name ?? null ?>" />
            </label>
            <label
            >Description
                <textarea placeholder="Description" name="category_description" value="<?=$editedCategory->description ?? null ?>"></textarea>
            </label>
            <label
            >Parent category
                <select name="category_parent">
                    <option value="null">--choose--</option>
                    <?php foreach ($selectListCategories as $category): ?>
                        <?php if(isset($editedCategory) && $editedCategory->parent_id == $category['id']): ?>
                            <option selected value="<?=$category['id']?>"><?=$category['name']?></option>
                        <?php else: ?>
                            <option value="<?=$category['id']?>"><?=$category['name']?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            </label>
            <input
                type="submit"
                class="button expanded"
                value="Save category"
            />
            </form>
        </div>

        <div class="medium-6 large-5 cell large-offset-1">
            <div class="basic-card">
                <div class="basic-card-content content callout secondary">
                    <h5><?=$category->name ?? 'Chose category from menu' ?></h5>
                    <?php if ($category->description): ?>
                        <p>
                            <?=$category->description ?? 'null' ?>
                        </p>
                    <?php endif; ?>
                </div>
                <?php if ($category): ?>
                    <div class="links callout primary">
                        <ul class="menu">
                            <li>
                                <a href="<?=$baseUrl?>edit-category/<?=$category->id?>" >Edit</a>
                            </li>
                            <li>
                                <a id="delete-category-confirmation" onclick="return confirm('Are you sure?')" href="<?=$baseUrl?>delete-category/<?=$category->id?>" >
                                    Delete
                                </a>
                            </li>
                        </ul>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <hr />
</div>
<?php include('layout/footer.phtml'); ?>

